update everything

diff --git a/.github/workflows/validate-manifest.yaml b/.github/workflows/validate-manifest.yaml
--- a/.github/workflows/validate-manifest.yaml
+++ b/.github/workflows/validate-manifest.yaml
@@ -22,9 +22,61 @@ concurrency:
   group: gitops-${{ github.ref }}
   cancel-in-progress: true
 jobs:
+  detect-changes:
+    name: Detect Changed Services
+    runs-on: ubuntu-latest
+    outputs:
+      helm-chart: ${{ steps.extract.outputs.services }}
+      helm-chart_changed: ${{ steps.extract.outputs.services_changed }}
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+  
+      - name: Paths Filter
+        id: filter
+        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d #vv4.0.1
+        with:
+          list-files: shell
+          filters: |
+            helm-chart:
+              - 'helm-chart/**'
+
+      - name: Extract helm chart services
+        id: extract
+        shell: bash
+        run: |
+          set -euo pipefail
+
+          HELM_FILES="${{ steps.filter.outputs.helm-chart_files }}"
+
+          if [ -n "$HELM_FILES" ]; then
+
+            MODIFIED_SERVICES=$(
+              echo "$HELM_FILES" \
+                | tr ' ' '\n' \
+                | cut -d'/' -f2 \
+                | sort -u \
+                | jq -R -s -c 'split("\n") | map(select(length>0))'
+            )
+
+            SERVICES="$MODIFIED_SERVICES"
+
+          else
+            SERVICES="[]"
+          fi
+
+          if [ "$SERVICES" != "[]" ]; then
+            echo "services_changed=true" >> "$GITHUB_OUTPUT"
+          else
+            echo "services_changed=false" >> "$GITHUB_OUTPUT"
+          fi
+
+          echo "services=$SERVICES" >> "$GITHUB_OUTPUT"
+
   yaml-lint:
     runs-on: ubuntu-latest
-
     steps:
       - name: Checkout repository
         uses: actions/checkout@v4
@@ -33,30 +85,6 @@ jobs:
         uses: ibiqlik/action-yamllint@v3
         with:
           file_or_dir: .
-
-  helm-check:
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v4
-
-      - name: Setup Helm
-        uses: azure/setup-helm@v4
-
-      - name: Helm lint
-        working-directory: helm
-        run: |
-            find . -name "Chart.yaml" | while read -r file ; do
-                dir=$(dirname "$file")
-                helm lint $dir
-            done
-
-      - name: Helm template render check
-        working-directory: helm
-        run: |
-            find . -name "Chart.yaml"  | while read -r file ; do
-                dir=$(dirname "$file")
-                helm template test $dir > /dev/null
-            done
 
   k8s-scan:
     name: " K8s manifest scan"
@@ -68,8 +96,128 @@ jobs:
       - name: Run Checkov on Kubernetes manifests
         uses: bridgecrewio/checkov-action@v12
         with:
-          directory: k8s/
+          directory: kubernetes-manifest/
           framework: kubernetes
           soft_fail: true  # Soft fail for K8s (some checks may not apply)
           output_format: cli
+
+  helm-check:
+    needs : detect-changes
+    runs-on: ubuntu-latest
+    if: needs.detect-changes.outputs.helm-chart_changed == 'true'
+    strategy:
+      fail-fast: false 
+      matrix:
+        helm-chart: ${{ fromJson(needs.detect-changes.outputs.helm-chart) }}
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Setup Helm
+        uses: azure/setup-helm@v4
+
+      - name: Helm lint
+        working-directory: helm-chart/${{matrix.helm-chart}}
+        run: |
+            find . -name "Chart.yaml" | while read -r file ; do
+                dir=$(dirname "$file")
+                helm lint $dir
+            done
+
+      - name: Helm template render check
+        working-directory: helm-chart/${{matrix.helm-chart}}
+        run: |
+            find . -name "Chart.yaml"  | while read -r file ; do
+                dir=$(dirname "$file")
+                helm template test $dir > /dev/null
+            done
+
+  release-helm-package:
+    name: " Release helm package"
+    runs-on: ubuntu-latest
+    outputs:
+      version: ${{ steps.chart_version.outputs.chart_version }}
+    permissions:
+      packages: write
+      contents: read 
+    needs: 
+      - detect-changes
+      - helm-check
+    if: | 
+      needs.detect-changes.outputs.helm-chart_changed == 'true' &&  
+      github.ref == 'refs/heads/main'
+    strategy:
+      fail-fast: false 
+      matrix:
+        helm-chart: ${{ fromJson(needs.detect-changes.outputs.helm-chart) }}
+    steps:
+    - name: Checkout code
+      uses: actions/checkout@v4
+
+    - name: Setup Helm
+      uses: azure/setup-helm@v4
+
+    - name: Setup yq
+      uses: dcarbone/install-yq-action@v1
+      with:
+        version: v4.47.2
+
+    - name: Login GHCR
+      run: |
+        echo "${{ secrets.GITHUB_TOKEN }}" | \
+        helm registry login ghcr.io \
+          --username "${{ github.repository_owner }}" \
+          --password-stdin
+
+    - name: Package and push helm chart
+      working-directory: helm-chart/${{ matrix.helm-chart }}
+      id: chart_version
+      run: |
+        set -e
+
+        if [ ! -f "Chart.yaml" ]; then
+          echo "Chart.yaml not found. Failed."
+          exit 1
+        fi
+
+        if [ ! -f "values.yaml" ]; then
+          echo "values.yaml not found. Failed."
+          exit 1
+        fi
+
+        echo "Packaging chart..."
+
+        PACKAGE_FILE=$(helm package . | awk '{print $NF}')
+        CHART_VERSION=$(yq '.version' Chart.yaml)
+
+        echo "chart_version=$CHART_VERSION" >> "$GITHUB_OUTPUT" 
+
+        echo "Pushing ${PACKAGE_FILE}:${CHART_VERSION} to GHCR..."
+
+        helm push "${PACKAGE_FILE}" \
+          oci://ghcr.io/${{ github.repository_owner }}/helm
+        
+        echo "Successfully pushed ${CHART_NAME}:${CHART_VERSION}"
+  update-kustomize-manifest:
+    name: " Update kustomize manifest"
+    needs: 
+      - release-helm-package
+      - detect-changes
+    runs-on: ubuntu-latest
+    if: |   
+      github.ref == 'refs/heads/main'
+    strategy:
+      fail-fast: false 
+      matrix:
+        helm-chart: ${{ fromJson(needs.detect-changes.outputs.helm-chart) }}
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+      
+      # - name: update kustomize manifest 
+      #   working-directory: 
+
+        
+       
+      
+
  
